// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TVBroadcastScheduler.Data;

#nullable disable

namespace TVBroadcastScheduler.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250718121853_SeedBroadcastsData")]
    partial class SeedBroadcastsData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TVBroadcastScheduler.Models.Broadcast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApprovalComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Channel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Broadcasts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Daily",
                            Channel = "BBC News",
                            CreatedBy = "scheduler",
                            Description = "Start your day with fresh updates and music.",
                            EndTime = new DateTime(2025, 7, 20, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2025, 7, 20, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            Title = "English Morning Show"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Daily",
                            Channel = "CNN",
                            CreatedBy = "scheduler",
                            Description = "World economy & stock news.",
                            EndTime = new DateTime(2025, 7, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2025, 7, 20, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            Title = "Business Buzz"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Daily",
                            Channel = "Discovery",
                            CreatedBy = "scheduler",
                            Description = "Latest in gadgets and innovation.",
                            EndTime = new DateTime(2025, 7, 20, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2025, 7, 20, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            Title = "Tech Talk Live"
                        });
                });

            modelBuilder.Entity("TVBroadcastScheduler.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
